language: java
jdk: oraclejdk10
install: mvn clean install -DskipTests=true
script: mvn test jacoco:report
after_success: mvn sonar:sonar -Dsonar.login=$sonarRepoToken -Dsonar.organization=$sonarOrganization -Dsonar.host.url=$sonarHostUrl
